### ISSUE TITLE
Site additions

### ISSUE THREAD

**Issue by nateify** [Boastful1353/ITJobSpam#1]
A couple of additions to suggest:
quantumworld.us
techdigitalcorp.com

I also noticed a modest amount of spammy job solicitations coming from different domains but the signatures and/or DKIM include one of these two domains:
joboppforyou.com
jobopportunityforyou.com

It would require a different type of email filter rule based on body or header.

**Comment by Boastful1353** [comment]
Ah good catch! I had not noticed that signing domain. Gmail does not appear to offer an option to filter those. https://support.google.com/mail/answer/7190?hl=en 
I'll continue to research this further but so far it doesn't look like gmail users can filter the signed-by or mailed-by fields. For now i have added all of those domains to the list. Thanks for contributing!

**Comment by Boastful1353** [comment]
Sending Feedback to GMAIL:

https://support.google.com/mail/answer/9212652?hl=en&co=GENIE.Platform%3DDesktop&sjid=3528784915408591875-NA&oco=2

I am currently facing a persistent problem with unsolicited communication from IT recruiters based in India. To address this issue, I have initiated a project aimed at mitigating this nuisance. I invite you to peruse my Reddit thread for further insights on this matter: https://www.reddit.com/r/sysadmin/comments/12zk6a2/it_recruiter_spam_2023/.

Upon careful examination, I have observed that a significant portion of the spam originates from identical "mailed-by" or "signed-by" domains. I would highly appreciate it if you could provide us with the facility to establish filters targeting these specific fields, thereby effectively curbing the inflow of spam.
